### ISSUE TITLE
make binding assignment to data less terrible

### ISSUE THREAD

**Issue by usevector** [cudagrad/cudagrad#4]
I had thought before using pybind11 OPAQUE_TYPE (I might misremember what it's called) would help but I'm not certain

**Comment by usevector** [comment]
```py
>>> import cudagrad as cg
>>> cg.Tensor([1], [1.0])
<cudagrad.Tensor([1, ], [1, ]) object at 0x600000b9c000>
>>> t = cg.Tensor([1], [1.0])
>>> t
<cudagrad.Tensor([1, ], [1, ]) object at 0x600000b98000>
>>> t[0]
1.0
>>> import torch
>>> t = torch.tensor([1.0], requires_grad=True)
>>> t
tensor([1.], requires_grad=True)
>>> t[0]
tensor(1., grad_fn=<SelectBackward0>)
```

**Comment by usevector** [comment]
```py
>>> t.size()
torch.Size([1])
>>> t[0].size()
torch.Size([])
```
our indexing is wack

**Comment by usevector** [comment]
^ in the sense that indexing shouldn't return `.data` it returns a `Tensor`

**Comment by usevector** [comment]
oh man we have to learn how `slice` works...

**Comment by usevector** [comment]
`slice` semantics is too big of a step and not really important to me right now, we actually just want multidimensional single element indexing to work

**Comment by usevector** [comment]
consider the following young padawan...

```cpp
  // The following overloads are very intruiging.  Consider the following
  // program:
  //
  //    x[1] = 3;
  //
  // We would expect that the first entry of x is written to 3.  But how can we
  // actually achieve this?  x[1] evaluates to a tensor...
  //
  // The answer is, using a ref-qualifier.  x[1] is an rvalue, which cannot be
  // (profitably) assigned to in the traditional sense, so we overload
  // assignment to mean, "Actually, copy 3 into the tensor data."  This is done
  // with an rvalue-reference ref-qualified overload (the methods with && at the
  // end of their type.)
  //
  // There's one more fly in the ointment: We also want
  //
  //    Tensor x = y;
  //
  // to work, and we want it NOT to copy.  So we need a traditional operator=
  // overload.  But we MUST specify a mutable lvalue ref-qualifier, to
  // disambiguate the traditional overload from the rvalue-reference
  // ref-qualified overload.  Otherwise, it will be ambiguous, because
  // a non ref-qualified method is eligible for all situations.
```
https://github.com/pytorch/pytorch/blob/4ee179c9528c8c6aae17a01f2b0d7e8235219219/aten/src/ATen/templates/TensorBody.h#L161

**Comment by usevector** [comment]
![](http://blog.ezyang.com/img/pytorch-internals/slide-06.png)

![](http://blog.ezyang.com/img/pytorch-internals/slide-07.png)

![](http://blog.ezyang.com/img/pytorch-internals/slide-08.png)

**Comment by usevector** [comment]
I remember my thought process from a few months ago... Yes, I could do something where I get a tuple of numbers I dot product with strides and then I access in linear memory (data vector) and get the answer.

BUT then what happens when you want to do assignment of a list, or like multiple values, then were back at slices right now (https://github.com/cudagrad/cudagrad/issues/7)? Do I care enough about that to do it right now or is it unimportant?

**Comment by usevector** [comment]
I think being able to do multidimensional indexing in C++ land with `t[4][2][0]` and Python land with `t[4, 2, 0]` would be a win...

Now I think this is how PyTorch does the indexing semantics but you should double check, I almost wonder if something like `.at({4, 2, 0})` would be better I don't know

**Comment by usevector** [comment]
https://pytorch.org/cppdocs/notes/tensor_indexing.html

### Getter
**Python**                                               | **C++ (assuming using namespace torch::indexing)**
----------------------------------------------------------|--------------------------------------------------
`tensor[None]`                                           | `tensor.index({None})`
`tensor[Ellipsis, ...]`                                  | `tensor.index({Ellipsis, "..."})`
`tensor[1, 2]`                                           | `tensor.index({1, 2})`
`tensor[True, False]`                                    | `tensor.index({true, false})`
`tensor[1::2]`                                           | `tensor.index({Slice(1, None, 2)})`
`tensor[torch.tensor([1, 2])]`                           | `tensor.index({torch::tensor({1, 2})})`
`tensor[..., 0, True, 1::2, torch.tensor([1, 2])]`       | `tensor.index({"...", 0, true, Slice(1, None, 2), torch::tensor({1, 2})})`

### Setter
**Python**                                               | **C++ (assuming using namespace torch::indexing)**
----------------------------------------------------------|--------------------------------------------------
`tensor[None] = 1`                                       | `tensor.index_put_({None}, 1)`
`tensor[Ellipsis, ...] = 1`                              | `tensor.index_put_({Ellipsis, "..."}, 1)`
`tensor[1, 2] = 1`                                       | `tensor.index_put_({1, 2}, 1)`
`tensor[True, False] = 1`                                | `tensor.index_put_({true, false}, 1)`
`tensor[1::2] = 1`                                       | `tensor.index_put_({Slice(1, None, 2)}, 1)`
`tensor[torch.tensor([1, 2])] = 1`                       | `tensor.index_put_({torch::tensor({1, 2})}, 1)`
`tensor[..., 0, True, 1::2, torch.tensor([1, 2])] = 1`   | `tensor.index_put_({"...", 0, true, Slice(1, None, 2), torch::tensor({1, 2})}, 1)`

### Translating between Python/C++ index types
The one-to-one translation between Python and C++ index types is as follows:

**Python**            | **C++ (assuming using namespace torch::indexing)**
----------------------|--------------------------------------------------
`None`                | `None`
`Ellipsis`            | `Ellipsis`
`...`                 | `"..."`
`123`                 | `123`
`True`                | `true`
`False`               | `false`
`:` or `::`           | `Slice()` or `Slice(None, None)` or `Slice(None, None, None)`
`1:` or `1::`         | `Slice(1, None)` or `Slice(1, None, None)`
`:3` or `:3:`         | `Slice(None, 3)` or `Slice(None, 3, None)`
`::2`                 | `Slice(None, None, 2)`
`1:3`                 | `Slice(1, 3)`
`1::2`                | `Slice(1, None, 2)`
`:3:2`                | `Slice(None, 3, 2)`
`1:3:2`               | `Slice(1, 3, 2)`
`torch.tensor([1, 2])`| `torch::tensor({1, 2})`

**Comment by usevector** [comment]
indexing with tensors is also not important to me right now

**Comment by usevector** [comment]
mmm lmao:
```py
>>> c = cg.Tensor([1], [1.0])
>>> c
<cudagrad.Tensor([1, ], [1, ]) object at 0x600000b98000>
>>> c.size
[1]
>>> c[0]
1.0
>>> cg.Tensor([],[1,0])
<cudagrad.Tensor([], [1, 0, ]) object at 0x600000b980a0>
>>> cg.Tensor([],[1.0])
<cudagrad.Tensor([], [1, ]) object at 0x600000b8e9e0>
>>> cg.Tensor([],[])
<cudagrad.Tensor([], []) object at 0x600000bb4000>
>>> cg.Tensor([],[]).size
[]
>>> cg.Tensor([],[1.0]).size
[]
```

```py
>>> t
tensor([1.], requires_grad=True)
>>> t[0]
tensor(1., grad_fn=<SelectBackward0>)
>>> 
>>> t.backward()
>>> t[0].backward()
>>> 
>>> 
```

**Comment by usevector** [comment]
did u know there's three (maybe more) indexing backwards classes in pytorch:

```py
>>> t = torch.tensor([[0, 1], [2, 3]], dtype=torch.float32, requires_grad=True)
>>> t[torch.tensor([1])]
tensor([[2., 3.]], grad_fn=<IndexBackward0>)
>>> t[0:1]
tensor([[0., 1.]], grad_fn=<SliceBackward0>)
>>> t[0]
tensor([0., 1.], grad_fn=<SelectBackward0>)
```

okay so we only need to do select, as far as I can tell it's only for single element

**Comment by usevector** [comment]
uhh great success? this repr/str is kinda wack though
```py
Successfully installed cudagrad-0.0.43

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
(main) Ryans-MacBook-Air:cudagrad ryan$ python
Python 3.10.8 (main, Nov 30 2022, 20:34:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudagrad as cg
>>> t = cg.Tensor([1], [1.0])
>>> t
<cudagrad.Tensor([1, ], [1, ]) object at 0x600000220000>
>>> t[0]
1.0
>>> type(t)
<class 'cudagrad.Tensor'>
>>> ??
```

**Comment by usevector** [comment]
oh nope thats type of `t` not `t[0]`

**Comment by usevector** [comment]
I don't know what's happening, but I do know I was editing DataProxy's `__getitem__` but actually no what matters is `Tensor`'s `__getitem__`

```
Successfully installed cudagrad-0.0.43

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
(main) Ryans-MacBook-Air:cudagrad ryan$ python
Python 3.10.8 (main, Nov 30 2022, 20:34:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudagrad as cg
>>> t = cg.Tensor([1], [1.0])
>>> t
<cudagrad.Tensor([1, ], [1, ]) object at 0x600003ac8000>
>>> t[0]
1.0
>>> 
(main) Ryans-MacBook-Air:cudagrad ryan$ cd src
(main) Ryans-MacBook-Air:src ryan$ ls
bindings.cpp	ops.cu		tensor.hpp
(main) Ryans-MacBook-Air:src ryan$ cling -l "tensor.hpp"

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ auto t = cg::tensor({1}, {1.0})
(std::shared_ptr<cg::Tensor> &) std::shared_ptr -> 0x600001750918
[cling]$ t
(std::shared_ptr<cg::Tensor> &) std::shared_ptr -> 0x600001750918
[cling]$ t.get()->get_data_at(1)
(std::shared_ptr<cg::Tensor>) std::shared_ptr -> 0x600001750b58
```

**Comment by usevector** [comment]
something something needed to pip cache purge or editable install I should make an alias to type that all out...

```
c>>> cg.Tensor
<class 'cudagrad.Tensor'>
>>> cg.Tensor([1], [1.0]).foo
<bound method PyCapsule.foo of <cudagrad.Tensor([1, ], [1, ]) object at 0x600001d0c140>>
>>> cg.Tensor([1], [1.0]).foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo(): incompatible function arguments. The following argument types are supported:
    1. (self: int) -> int

Invoked with: <cudagrad.Tensor([1, ], [1, ]) object at 0x600001d0c1e0>
>>> cg.Tensor([1], [1.0]).foo(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo(): incompatible function arguments. The following argument types are supported:
    1. (self: int) -> int

Invoked with: <cudagrad.Tensor([1, ], [1, ]) object at 0x600001d08000>, 1
>>> cg.Tensor([1], [1.0]).dummy
<bound method PyCapsule.dummy of <cudagrad.Tensor([1, ], [1, ]) object at 0x600001d0c1e0>>
>>> cg.Tensor([1], [1.0]).dummy(1)
wtf
<cudagrad.Tensor([1, ], [0, ]) object at 0x60000190c018>
>>> t = cg.Tensor([1], [1.0])
>>> t
<cudagrad.Tensor([1, ], [1, ]) object at 0x600001d14000>
>>> t[0]
wtf
<cudagrad.Tensor([1, ], [1, ]) object at 0x600001908018>
>>> 
```
b043a20305de718c0b4fbe7b2a470768ebe1c927

**Comment by usevector** [comment]
```py
>>> cg.Tensor([1], [1.0]).dummy(1)
wtf
<cudagrad.Tensor([1, ], [0, ]) object at 0x60000190c018>
>>> t = cg.Tensor([1], [1.0])
>>> t
<cudagrad.Tensor([1, ], [1, ]) object at 0x600001d14000>
>>> t[0]
wtf
<cudagrad.Tensor([1, ], [1, ]) object at 0x600001908018>
```

```py
>>> t = torch.tensor([1.0], requires_grad=True)
>>> t
tensor([1.], requires_grad=True)
>>> t[0]
tensor(1., grad_fn=<SelectBackward0>)
```

**Comment by usevector** [comment]
73628279e4753de92b1445d7463af1fecbb4bb5b
```py
>>> t = cg.Tensor([2, 2], range(4))
>>> t
<cudagrad.Tensor([2, 2, ], [0, 1, 2, ...]) object at 0x600000544000>
>>> t[[1, 0]]
<cudagrad.Tensor([1, ], [2, ]) object at 0x600000140018>
```

`[[]]` is weird:

```py
>>> arr = np.array(range(4)).reshape(2,2)
>>> arr
array([[0, 1],
       [2, 3]])
>>> arr[1, 0]
2
```

**Comment by usevector** [comment]
I think I'll have broken the tests...
